name: donggyu lee's blog
repository: "donggyuu/donggyuu.github.io"
description: 'notes and thoughts from dong'

url: 'https://donggyuu.github.io'
baseurl:

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'donggyu lee'
disqus_shortname: donggyuu-github-io
google_analytics: 

plugins:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed
